spring:
  application:
    name: gateway
    profiles:
      active: dev
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
  instance:
    hostname: ${spring.cloud.client.ipAddress}
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
